### ISSUE TITLE
Remove fbid on photo links

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Mte90/facebook-direct-links#11]
Could you add the option to remove fbid tags?

**Comment by Mte90** [comment]
Sorry I missed that ticket, they should be already removed.
Can I have an eexample where is not working?

**Comment by cgcgcgcgcg** [comment]
> Sorry I missed that ticket, they should be already removed.
> Can I have an eexample where is not working?

https://www.facebook.com/photo.php?fbid=1376555745836666&set=p.1376555745836666&type=3&eid=ARAl1JFtHToGT_DjT0D14mO3RfgR-khKZ44M09oK8QQh8zZl3Lmz1WOiDL4RHC1pJurL7HCwscZSOWm2

**Comment by cgcgcgcgcg** [comment]
One of the side-effects of the fbid is for example on pics that makes the Imagus extension not work on some, for example in pics that are in comments -Imagus dev answered he won't be bothered to fix it since fbid additions include pic information and pics won't work if fbid full addition data is removed.

That means that your extension and similar ones will not affect extensions like Imagus anyways since it handles clicked links and cleans them.

FB is saying next to nothing about fbid, we know it's a tracking component, and now it made it hard or impossible to remove since it implements crucial info about the link (eg the pic).

**Comment by Mte90** [comment]
Quite sad but fbid is something understandable, probably the `eid` parameter is useless and used for tracking. Fbid is used as id of the photo.
