### ISSUE TITLE
Query selector does not return the correct links

### ISSUE THREAD

**Issue by androsanta** [Mte90/facebook-direct-links#12]
It can be easily checked by running `document.querySelectorAll('a:not([role])')` in the console, which returns an empty list

Maybe it is caused by the new Facebook redesign, looking at the html it seems that every link has a `role="link"` attribute.

Does extending the query on all `a` tags results in lower performance?

**Comment by Mte90** [comment]
I saw various problems with the new design but I didn't get time to investigate  so any help link this is very appreciated.

The problem is that in FB every button is a link (or a link with inside a button) so I saw that detect that attribute at the time was a way to exclude "button links".

**Comment by androsanta** [comment]
Thank you for the fast reply!

If it's ok I'll investigate and try finding a solution. I'll report any update :)

**Comment by Mte90** [comment]
Yes of course if you need help with the extension development let me know.
Any help is very appreciated :-D

**Comment by androsanta** [comment]
Hi 😁, so I've done some tests and this is what i found out:
* extending the links selector from `a:not([role])` to `a` does not impact performance
* the new site structure makes use of iframes (in messenger for example) so links inside those tags are not considered

To address the 2nd point I've tried the following:

```
ready( 'iframe', function ( iframe ) {
    // A new observer for the iframe document
    var obs = null

    // Create a new observer and call check to update elements
    var startObserving = d => {
        obs = new MutationObserver( () => {
            check( null, null, d )
        } )
        obs.observe( iframe.contentWindow.document, { childList: true, subtree: true } )
        check( null, null, d )
    }

    /*
    Disconnect observer for that iframe
    but check if the window has been destroyed completely
    or has been recreated, if so, recreate also the observer
    */
    iframe.contentWindow.onunload = () => {
        if ( obs ) {
            obs.disconnect()
        }
        setTimeout( () => {
            // If the window has been recreated recreate also the observer
            if ( iframe.contentWindow ) {
                startObserving( iframe.contentWindow.document )
            }
        }, 0 )
    }

    // Actually create the observer
    startObserving( iframe.contentWindow.document )
} )
```

Create another entry on `listeners` by means of `ready` function so that both `a` and `iframe` tags are queried.
Once an iframe is found a new observer is created, observing the iframe document this time.
Then the already working flow continue (check -> listener callback -> cleanup -> updateElement).
The only difference is that the check function can accept a different document on which execute the query selector (that document will be different for each iframe):

`function check(mutationsList, observer, doc = mainDoc) {}`


Note: the unload callback for the iframe is necessary as it seems that sometimes the iframe is loaded and unloaded multiple times (I imagine it could be caused by a web framework like react).


I was unable to test if there's a performance impact with this 2nd solution as firefox does not show temporary extension in the performance tab

If it's ok a can create a pull request 😄

**Comment by Mte90** [comment]
Yes, just do a pull request so I can do some testing :-D
I think that don't create any performance problem because the code is very simple.

**Comment by androsanta** [comment]
I've created a pull request, it's my first one so if you have any hints you're welcome 😄

**Comment by Mte90** [comment]
new version released on firefox :-)
