### ISSUE TITLE
Doesn’t work anymore (since Facebook new version?)

### ISSUE THREAD

**Issue by pols12** [Mte90/facebook-direct-links#14]
This extension doesn’t work anymore at home. This is probably since Facebook has upgraded.

**Comment by Mte90** [comment]
I am not using the new design right now, can you confirm that with the new one is not working?

**Comment by pols12** [comment]
Yes, I just tested and I can confirm: switching to the old design solves the problem.

**Comment by ShamrockLee** [comment]
I can confirm that the extension doesn't work anymore on the new theme of Facebook.
BTW, Facebook is going to permanently deprecate the classic theme after Sep. 1st.

When loading the page
http://forums.debian.net/viewtopic.php?f=10&t=146941
from the link preview of the post
https://www.facebook.com/groups/lifewithdebian/permalink/10157474432943977/

The initial URL is
https://l.facebook.com/l.php?u=http%3A%2F%2Fforums.debian.net%2Fviewtopic.php%3Ff%3D10%26t%3D146941%26fbclid%3Dblablabla&h=blablabla&__tn__=H-R&c[0]=blablabla
and the URL of the loaded page is
http://forums.debian.net/viewtopic.php?f=10&t=146941&fbclid=blablabla

Here is the screenshot:
![Screenshot_20200824_054351_cropped](https://user-images.githubusercontent.com/44064051/90989761-cf2bcf80-e5ce-11ea-81f9-325b80d7523f.png)

**Comment by Mte90** [comment]
I am testing in 2 different browsers and I don't see that problem.
What version of the extension do you have? the last 1.2.0 should include already the support

**Comment by ShamrockLee** [comment]
@Mte90 It's 1.2.0 in Mozilla Firefox.

**Comment by Mte90** [comment]
I tried on Firefox 80 with that just this extension installed and is working.
Maybe there are some extension that creates conflicts?

**Comment by Mte90** [comment]
I was able to replicate the issue so I am releasing a new version with the fix (i hope).

**Comment by pols12** [comment]
Thank you for your work. However, I use right click (contextual menu) → Copy link address, and this still doesn’t work. 😢

**Comment by Mte90** [comment]
I am doing the cleanup with 3/4 events and includes also the contextmenu and doesn't work when the menu is opened and you copy (tried), to me they have a timer or something like that to reinject the tracker.
In fact when you open the contextmenu the url is cleaned but when click on copy it doesn't anymore.

To fix I should implement a timer too and I don't like the idea.

**Comment by pols12** [comment]
Yeah I saw, this is totally crazy! :disappointed:
