### ISSUE TITLE
Internal links are blocked

### ISSUE THREAD

**Issue by moonshaadow** [Mte90/facebook-direct-links#15]
Hey there!
I use the addon on firefox for android.
It works perfectly for external links, but I cannot use internal links anymore.

**Comment by Mte90** [comment]
With the new design?
Can I have some screenshots of the issue? I need to replicate

**Comment by moonshaadow** [comment]
Not with the new design.
![Screenshot_20200904-104809](https://user-images.githubusercontent.com/29754932/92220712-ae039280-ee9c-11ea-9036-2817b54979a1.jpeg)

I can long-press on it, but opening in a new tab generate a new feed.

**Comment by Mte90** [comment]
It seems from mobile i am right?

**Comment by moonshaadow** [comment]
Yes. Android.

**Comment by moonshaadow** [comment]
Links outside fb work as expected. Links inside don't.

**Comment by Mte90** [comment]
So we are talking of Firefox 68 that is not supported anymore by mozilla because extensions in Firefox for android right now are disabled.
