### ISSUE TITLE
Extension don’t allow to mark notifications as read

### ISSUE THREAD

**Issue by pols12** [Mte90/facebook-direct-links#17]
(probably a regression by f9483e8)

When you click on the filled circle of a notification to mark it as read, you are redirected to redirection link and the notification remains in unread state.

**Comment by Mte90** [comment]
It wasn't easy to spot this one!

**Comment by pols12** [comment]
Sadly, version 1.2.2 does not fix this issue.

**Comment by Mte90** [comment]
On my Facebook is working, if I cannot replicate the issue I cannot fix it...

**Comment by pols12** [comment]
You whitelisted `&notif_t=feedback_reaction_generic`, but this depends on notification type, I could seen the following one on my recent notifications:
* `&notif_t=feed_comment`
* `&notif_t=event_joined_nearby`
* `&notif_t=admin_plan_mall_activity`
* `&notif_t=feed_comment_follow`
* `&notif_t=event_mall_reply`
* `&notif_t=event_friend_going`
* `&notif_t=birthday_reminder`
* `&notif_t=aymt_biz_growth_gain_fan_upsell_tip`
* `&notif_t=event_calendar_create`
* `&notif_t=added_to_group_reminder`
* `&notif_t=plan_edited`
* `&notif_t=admin_plan_mall_activity`
* `&notif_t=friend_confirmed`

Maybe whitelisting `&ref=notif` is safer?

**Comment by Mte90** [comment]
Good catch I didn't saw that, I will do something more generic

**Comment by Mte90** [comment]
I am releasing a new version with that fix
