### ISSUE TITLE
This add-on breaks Disqus comments

### ISSUE THREAD

**Issue by Moilleadoir** [Mte90/facebook-direct-links#19]
With this add-on enabled, the Disqus comments section on [OMG! Ubuntu!](https://www.omgubuntu.co.uk) is not loaded. I’m surprised it’s not limited to the facebook.com domain.

**Comment by Moilleadoir** [comment]
It might have just been a co-incidence. Other people have had problems with comments on the site since.

**Comment by Mte90** [comment]
Usually Disqus has issue with the Firefox 3rd party protection
