### ISSUE TITLE
Consider to also remove more query string? Like  `utm_` / `fb_` series ...

### ISSUE THREAD

**Issue by PeterDaveHello** [Mte90/facebook-direct-links#21]
It could be a little bit more aggressive or out of topic, because I saw some of the query strings will be removed here: https://github.com/Mte90/facebook-direct-links/blob/48645d5a8823e52128e2c3555bdf23d7932be826/direct.js#L58-L62, just wondering if you'd also like to make the URL more clean? I could send some PRs if you want, but if that's not something should be done in this extension, please feel free to close this issue ;)

**Comment by PeterDaveHello** [comment]
Maybe `__cft__*` could also be removed ...

**Comment by Mte90** [comment]
I think too.

**Comment by PeterDaveHello** [comment]
The reason it doesn't work is because the link is not an external link, so should be issue #28 ;)
