### ISSUE TITLE
Current clean up method might cause some problems

### ISSUE THREAD

**Issue by PeterDaveHello** [Mte90/facebook-direct-links#24]
e.g.

```js
uri = 'https://123.com/?ref=1234&fb_ref=4567'
uri = uri.replace(/&?ref=[^&#$/]*/gi, '');
```

The result will be: `https://123.com/?&fb_` which I assume is not what we expected.

Ref:
https://github.com/Mte90/facebook-direct-links/blob/777654b13256461542e43b42a6e7158ccbef62b3/direct.js#L59

**Comment by Mte90** [comment]
Uhm the issue is that facebook use that parameter as I can remember but I don't know if it is doing after the new UI.

**Comment by PeterDaveHello** [comment]
The problem will not only happen on facebook, but all parameters end with `ref`, e.g.

```js
uri = 'https://123.com/?site_ref=4567'
uri = uri.replace(/&?ref=[^&#$/]*/gi, '');
```

The result of the uri will be: `https://123.com/?site_`

**Comment by PeterDaveHello** [comment]
The match pattern needs to confirm if it's matching the whole query string parameter, not just the end of it.

**Comment by Mte90** [comment]
You are right can you do a PR?
Maybe it's the case to do it for all of them.

**Comment by PeterDaveHello** [comment]
I'll take a while to see which implementation would be more suitable, but I don't think you need to wait for that, as I can not commit a date time to do so.

**Comment by Mte90** [comment]
Released a new version with the latest changes for Firefox :-)

**Comment by PeterDaveHello** [comment]
Nice, BTW, the git tag seemed to be missed: https://github.com/Mte90/facebook-direct-links/releases / https://github.com/Mte90/facebook-direct-links/tags

**Comment by Mte90** [comment]
Oh quite simple, I forgot it 😂

**Comment by PeterDaveHello** [comment]
Could consider to enable some CI flow to automatically trigger the release from git tag, with some tests and lints to ensure the quality ;)

**Comment by Mte90** [comment]
Yes I have already on other extension but this one as so ffew updates that right now is not worth it.
I mean this was the first release in an year 😅

**Comment by PeterDaveHello** [comment]
Just got a though of some ugly workaround:

```diff
- uri = uri.replace(/&?ref=[^&#$/]*/gi, '');
+ uri = uri.replace(/([&|?])ref=[^&#$/]*/gi, '$1');
```

The result is not pretty, will make sure there is a leading `?` or `&`, and just keep it, instead of remove it, not looking good, but at least won't break things, what do you think?

**Comment by PeterDaveHello** [comment]
```js
uri = 'https://123.com/?ref=4567&fb_ref=123&ref=333&jdksaldref=123213'
uri = uri.replace(/([&|?])ref=[^&#$/]*/gi,'$1')
```

The result will be: `https://123.com/?&fb_ref=123&&jdksaldref=123213`

```js
uri = 'https://123.com/?ref=4567&fb_ref=123&ref=333&jdksaldref=123213'
uri = uri.replace(/([&|?])ref=[^&#$/]*/gi,'$1')
```

The result will be: `https://123.com/?&fb_&jdksald`

**Comment by Mte90** [comment]
uhm we need to remove the `fb_` parameter to do a good job, I guess that with a bit of regex we can do it.

**Comment by PeterDaveHello** [comment]
@Mte90 we sure do, the example doesn't contain the match of `fb_ref` regex, just to demo that it won't faulty remove something. Some final improvement can come after those replacement, to remove duplicated `&`.

**Comment by Mte90** [comment]
Perfect :-)
Waiting for the PR :-D

**Comment by PeterDaveHello** [comment]
Sure, I'll prepare it.
