### ISSUE TITLE
[regression] Many natural Facebook ajax actions are broken

### ISSUE THREAD

**Issue by pols12** [Mte90/facebook-direct-links#31]
Many Ajax actions are now broken:
* Clicking on Notifications icon leads to https://www.facebook.com/notifications/ instead of displaying notification box.
* From notification page, clicking on blue circle opens notification link instead of marking it as read.
* Clicking on a photo opens /photo link instead of displaying it in a lightbox (so we are obliged to use browser Previous page feature, because there is no more Cross symbol to close the photo light box).
…

Probably a v1.3.3 regression (#30).

**Comment by Mte90** [comment]
I was getting the same issues.
@PeterDaveHello those were my doubts about the cleaning of internal actions.
If you can't fix it in the next days I will remove the latest changes and do a new release.

**Comment by PeterDaveHello** [comment]
Should be my fault, let's revert it: #32

**Comment by Mte90** [comment]
New version released with the revert of that feature.
