### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Mte90** [Mte90/facebook-direct-links#4]
This extension can be installed on Firefox for android but the event is only on mousedown and not on tap or if someone do a long pressure that open the popup with the button to open it on a new tab.

**Comment by Mte90** [comment]
we can add https://github.com/john-doherty/long-press

**Comment by cipharius** [comment]
It should just work fine with `touchstart` event, as that will fire
for both regular tap and long press. Problem is that mobile facebook
site still has the long redirection links, for example:
`https://lm.facebook.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-O5kNPlUV7w%26fbclid%3DIwAR37bYdIbFgPZtiP8bSawdQGVJDysUMyf4WjMXJCZEjS8r131TuqPUx3pZM&h=AT1uxCj9wPh9G0Zpa(..)`

I suppose one could `decodeURIComponent`, check if the URI is of form `lm.facebook.com` or `l.facebook.com` and then extract the `u` parameter content. First version could just use some
dirty regexp and see how robust that is in real life situations.

**Comment by Mte90** [comment]
seems quite complicated but is something that is possible to achieve

**Comment by cipharius** [comment]
It seems that most annoying part is that original URIs themselves can have
parameters as well, so I can't decode the URI first. It seems that the `u` parameter
has to be extracted first and only then it may be decoded and set as element's href.

I'll give it a try later at home and see how well that holds up by clicking bunch of 
different links.

On another note, it does start to feel dirty using regexp for manipulating with URIs. 
Possibly functions that extract parameters in cleaner way may be added as future features.
